### PR TITLE
Master

### PR DESCRIPTION
**Pull request by thinkingofmaud**
Add pt-BR and disqus support

### CODE REVIEW

**Comment by icylogic** [comment]
Would you like to create a new Pull Request?

**Comment by thinkingofmaud** [comment]
Mr Icylogic, I will create a new Pull request later this week, I think. There's still some bugs on the disqus support. I'm working on that. I'm learning jade now, and i'm also new to hexo and github.

Anyway, thanks for your theme. I think it's the cleaner one on the hexo gallery!

There are some things on your code that I dont understand. Will it bother you if I create a branch and put some comments on some lines of code?

**Comment by icylogic** [comment]
In fact, I've planned to add disqus support to this theme, but I'm busy these days, so I'd be grateful if you could help.

Make changes or put comments if you want. When you get confused about any part of this project, feel free to open an issue or send me an email. :)

**Comment by thinkingofmaud** [comment]
Got disqus working.

I think it's not possible to collapse/trigger the disqus thread as you do with duoshuo, since the disqus widget embeds an iframe inside #disqus_thread. For now, it's just inserted before the nav.
Maybe I can read the document inside the iframe and render it somewhere else, but is that even possible? I think it's isolated on an iframe as a security measure to prevent exactly that type of thing.

Is there some english introduction/tutorial to duoshuo? I want to test if I didn't break anything on your theme before issuing another pull request.

**Comment by icylogic** [comment]
Thanks for your work.

Unfortunately I couldn't find a English version of duoshuo's document. As for disqus, I think at least we can use jQuery.getScript() to load disqus on the click event of the comment button. (It seems a small trick is needed to get this work as mentioned in [this post](http://www.pleaselistencarefully.com/How-to-load-disqus-comments-asynchronously-bonus-and-why)).

Since you've finished the main part of this feature, you may open a pull request and I could try to help you this weekend.

**Pull request closed without merging**
